### ISSUE TITLE
Discrepancy in Routing class

### ISSUE THREAD

**Issue by inirudebwoy** [socek/qapla#3]
```python
   def add_view(self, controller, **kwargs):
        url = self._convert_url(controller)

        controller_class = self.config.maybe_dotted(url)

        for name in self.values_to_set:
            self.set_controller_config(kwargs, controller_class, name)

        self.config.add_view(url, **kwargs)

    def _convert_url(self, url):
        return url
```

`add_view` accepts controller argument which is passed into `_convert_url`. `_convert_url` seems to be expecting something else.

**Comment by socek** [comment]
It is hard to fix this, because this sample if code is a little bit fuzzy but needed.
https://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.maybe_dotted
`maybe_dotted` method will accept dotted url and return the controller_class, but it will also accept the controller_class itself. I do not have idea how to wright this in a better way.

**Comment by inirudebwoy** [comment]
OK, this was not clear from the code.
My take:

```python
   def add_view(self, controller, **kwargs):
        controller_class = self.config.maybe_dotted(controller)

        for name in self.values_to_set:
            self.set_controller_config(kwargs, controller_class, name)

        self.config.add_view(controller_class, **kwargs)
```

Since both methods `maybe_dotted` and `add_view` accept string (dotted name) or an instance of a class. `maybe_dotted` will simply return it while other will probably call it. 
Information of our `add_view` accepting string or class as `controller` argument  should be put in docstring so we won`t confuse anyone.

**Comment by inirudebwoy** [comment]
I'd remove `_convert_url`. Forgot to mention it.

**Comment by socek** [comment]
Fixed.
